[package]
name = "rofi-recent"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "4.0.0"
fork = "0.1.19"
linked-hash-map = "0.5.4"
regex = "1.5.6"
serde = { version = "1.0.136", features = ["derive"] }
serde-xml-rs = "0.5.1"
thiserror = "1.0.30"
urlencoding = "2.1.0"

